
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package smpl.lang;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int QUES = 35;
  public static final int LBRACKET = 28;
  public static final int CHAR = 46;
  public static final int CONCAT = 18;
  public static final int EMPTY = 50;
  public static final int READINT = 20;
  public static final int CAR = 9;
  public static final int INTEGER = 39;
  public static final int CDR = 10;
  public static final int LPAREN = 26;
  public static final int SEMI = 30;
  public static final int HEX = 44;
  public static final int PRINTLN = 14;
  public static final int MINUS = 22;
  public static final int REF = 8;
  public static final int RPAREN = 27;
  public static final int LCURL = 37;
  public static final int NOT = 36;
  public static final int RATIONAL = 48;
  public static final int BOOL = 47;
  public static final int COMMA = 31;
  public static final int LAZY = 7;
  public static final int CALL = 6;
  public static final int DIV = 24;
  public static final int PLUS = 21;
  public static final int IF = 51;
  public static final int ASSIGN = 2;
  public static final int EOF = 0;
  public static final int RBRACKET = 29;
  public static final int EQUAL = 16;
  public static final int SIZE = 3;
  public static final int error = 1;
  public static final int MOD = 25;
  public static final int PAIR = 11;
  public static final int REAL = 40;
  public static final int RCURL = 38;
  public static final int EQV = 15;
  public static final int TIMES = 23;
  public static final int COLON = 32;
  public static final int ELSE = 52;
  public static final int READ = 19;
  public static final int LIST = 12;
  public static final int SUBSTR = 17;
  public static final int THEN = 53;
  public static final int BINARY = 43;
  public static final int STRING = 42;
  public static final int PROC = 5;
  public static final int DEF = 13;
  public static final int LOGIC = 49;
  public static final int UNICODE = 45;
  public static final int LBCOLON = 33;
  public static final int RBCOLON = 34;
  public static final int VAR = 41;
  public static final int PRINT = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "SIZE",
  "PRINT",
  "PROC",
  "CALL",
  "LAZY",
  "REF",
  "CAR",
  "CDR",
  "PAIR",
  "LIST",
  "DEF",
  "PRINTLN",
  "EQV",
  "EQUAL",
  "SUBSTR",
  "CONCAT",
  "READ",
  "READINT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "SEMI",
  "COMMA",
  "COLON",
  "LBCOLON",
  "RBCOLON",
  "QUES",
  "NOT",
  "LCURL",
  "RCURL",
  "INTEGER",
  "REAL",
  "VAR",
  "STRING",
  "BINARY",
  "HEX",
  "UNICODE",
  "CHAR",
  "BOOL",
  "RATIONAL",
  "LOGIC",
  "EMPTY",
  "IF",
  "ELSE",
  "THEN"
  };
}

