
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package smpl.lang;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int QUES = 29;
  public static final int LBRACKET = 22;
  public static final int CHAR = 38;
  public static final int CAR = 6;
  public static final int INTEGER = 31;
  public static final int CDR = 7;
  public static final int LPAREN = 20;
  public static final int SEMI = 24;
  public static final int HEX = 36;
  public static final int PRINTLN = 11;
  public static final int MINUS = 16;
  public static final int RPAREN = 21;
  public static final int NOT = 30;
  public static final int RATIONAL = 40;
  public static final int BOOL = 39;
  public static final int COMMA = 25;
  public static final int DIV = 18;
  public static final int PLUS = 15;
  public static final int IF = 42;
  public static final int ASSIGN = 2;
  public static final int EOF = 0;
  public static final int RBRACKET = 23;
  public static final int EQUAL = 13;
  public static final int SIZE = 3;
  public static final int error = 1;
  public static final int MOD = 19;
  public static final int PAIR = 8;
  public static final int REAL = 32;
  public static final int EQV = 12;
  public static final int TIMES = 17;
  public static final int COLON = 26;
  public static final int ELSE = 43;
  public static final int LIST = 9;
  public static final int SUBSTR = 14;
  public static final int THEN = 44;
  public static final int BINARY = 35;
  public static final int PROC = 5;
  public static final int STRING = 34;
  public static final int DEF = 10;
  public static final int LOGIC = 41;
  public static final int UNICODE = 37;
  public static final int LBCOLON = 27;
  public static final int RBCOLON = 28;
  public static final int VAR = 33;
  public static final int PRINT = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "SIZE",
  "PRINT",
  "PROC",
  "CAR",
  "CDR",
  "PAIR",
  "LIST",
  "DEF",
  "PRINTLN",
  "EQV",
  "EQUAL",
  "SUBSTR",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "SEMI",
  "COMMA",
  "COLON",
  "LBCOLON",
  "RBCOLON",
  "QUES",
  "NOT",
  "INTEGER",
  "REAL",
  "VAR",
  "STRING",
  "BINARY",
  "HEX",
  "UNICODE",
  "CHAR",
  "BOOL",
  "RATIONAL",
  "LOGIC",
  "IF",
  "ELSE",
  "THEN"
  };
}

