
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package smpl.lang;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 16;
  public static final int CONCAT = 21;
  public static final int INTEGER = 22;
  public static final int LPAREN = 14;
  public static final int SEMI = 18;
  public static final int MINUS = 6;
  public static final int TILDE = 13;
  public static final int CMP = 28;
  public static final int RPAREN = 15;
  public static final int NOT = 36;
  public static final int AND = 34;
  public static final int FRACTION = 23;
  public static final int NIL = 31;
  public static final int OR = 35;
  public static final int COMMA = 19;
  public static final int DIV = 8;
  public static final int PLUS = 5;
  public static final int ASSIGN = 3;
  public static final int IF = 32;
  public static final int AMPERSAND = 11;
  public static final int CARET = 10;
  public static final int EOF = 0;
  public static final int RBRACKET = 17;
  public static final int TRUE = 29;
  public static final int error = 1;
  public static final int PIPE = 12;
  public static final int MOD = 9;
  public static final int REAL = 24;
  public static final int TIMES = 7;
  public static final int COLON = 20;
  public static final int ELSE = 33;
  public static final int QUESTION = 37;
  public static final int PROC = 2;
  public static final int STRING = 26;
  public static final int DEF = 4;
  public static final int BINARYHEX = 27;
  public static final int FALSE = 30;
  public static final int VAR = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROC",
  "ASSIGN",
  "DEF",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "CARET",
  "AMPERSAND",
  "PIPE",
  "TILDE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "SEMI",
  "COMMA",
  "COLON",
  "CONCAT",
  "INTEGER",
  "FRACTION",
  "REAL",
  "VAR",
  "STRING",
  "BINARYHEX",
  "CMP",
  "TRUE",
  "FALSE",
  "NIL",
  "IF",
  "ELSE",
  "AND",
  "OR",
  "NOT",
  "QUESTION"
  };
}

